### ISSUE TITLE
How to setup/build this project

### ISSUE THREAD

**Issue by thosi-yamada** [twilio-professional-services/flex-dialpad-addon-plugin#10]
I am not sure how to setup this. Tried to install, it seems ok. but I cannot start/build this project.
How do I configure for .env file?

>Error: Failed to find .env file at path: .env.development
    at getEnvFile

**Comment by kaiquelupo** [comment]
Hey! There are two .env files you need to create: .env.development and .env.production. The former is going to be used when you run the project locally and the latter will be used when you deploy to production. Therefore, copy the .env.example structure to both .env files as described previous. If you want to check this in the README.md file, it is the third step of the `How to use` section.
