### ISSUE TITLE
Agent to Agent Call Fails 

### ISSUE THREAD

**Issue by pledgera** [twilio-professional-services/flex-dialpad-addon-plugin#12]
Hi Team,

State of Illinois is having an issue with the agent to agent calling feature that the PS team helped them with a couple weeks back. The feature works perfect in Dev and QA, but for some reason it’s not working in UAT. They said they copied and pasted directly from their DEV environment and did not change anything.  When Madhu tries to call Srikanth it rings on her end but he never gets the call.  Have you seen this issue before?

 Issue: The feature shows up at the bottom of the dial pad and the available agents show up, but when you try to call them the agent never receives the call.

Deployment error message: “UnhandledPromiseRejectionWarning: Unhandled promise rejection: undefined” and the agent to agents calls are failing.

UAT Env account sid: AC5c8a7363e9a567f734203785611b6193

Link to code/solution from Kaique we used: https://github.com/twilio-professional-services/flex-dialpad-addon-plugin/commit/c27db42fba7fcfae04686c5535f39e3ff10dee5a?branch=c27db42fba7fcfae04686c5535f39e3ff10dee5a&diff=split#diff-5b6e7e0e599205c22dcda128b9daf7e3

2020-10-13 15:13:00 UTC
Execution started...
2020-10-13 15:13:00 UTC
WW99b411af2e29cd47f2ea627c15672daa" 2020-10-13T15:13:00.015Z 440e3848-9567-451f-93bd-5f28ff4a532a INFO {​​​​​​​ Coaching: 'false', FriendlyName: 'WT350f4f94fa597d49db96ec708e382768', SequenceNumber: '1', ConferenceSid: 'CFa060b5ff30e754508c226f8ab3bcb019', EndConferenceOnExit: 'true', CallSid: 'CA94d480a17b8e5e91eddb530b63ce8b10', StatusCallbackEvent: 'participant-join', Timestamp: 'Tue, 13 Oct 2020 15:12:59 +0000', StartConferenceOnEnter: 'true', Hold: 'false', AccountSid: 'AC5c8a7363e9a567f734203785611b6193', Muted: 'false' }​​​​​​​
2020-10-13 15:13:00 UTC
callSid CA94d480a17b8e5e91eddb530b63ce8b10 joined, task is WT350f4f94fa597d49db96ec708e382768, conference is CFa060b5ff30e754508c226f8ab3bcb019
2020-10-13 15:13:00 UTC
agent client:madhulika_2Eramabhotla_40slalom_2Ecom joined the conference
2020-10-13 15:13:00 UTC
yo are at addParticipantToConference
2020-10-13 15:13:00 UTC
yo are at addParticipantToConference if condition...
2020-10-13 15:13:00 UTC
UnhandledPromiseRejectionWarning: Unhandled promise rejection: undefined
2020-10-13 15:13:00 UTC
Execution ended in 257.2ms using 112MB

In /internal-call/call-outbound-join serverless function
const addParticipantToConference = (client, conferenceSid, taskSid, to, fromName) => {
    console.log('yo are at addParticipantToConference ');
  if (to.substring(0, 6) === 'client') {
    console.log('yo are at addParticipantToConference if condition... ' );
    return client
      .taskrouter.workspaces(process.env.TWILIO_WORKSPACE_SID)
      .tasks
      .create(
        {
          attributes: JSON.stringify(
            {
              to: to,
            //   direction: 'outbound',
              //name: from,
              name: fromName,
              from: process.env.TWILIO_NUMBER,
              targetWorker: to,
              autoAnswer: 'false',
              conferenceSid: taskSid,
              conference: {
                sid: conferenceSid,
                friendlyName: taskSid
              },
              internal: 'true',
              client_call: true,
            //   outbound_to: to
            }),
          workflowSid: process.env.TWILIO_WORKFLOW_SID,
          taskChannel: 'voice'
        })
  }

 
[flex.twilio.com-1602616040015.log](https://github.com/twilio-professional-services/flex-dialpad-addon-plugin/files/5373617/flex.twilio.com-1602616040015.log)
};
![image](https://user-images.githubusercontent.com/66129042/95905890-660f3f80-0d67-11eb-8e32-9001dce208c8.png)
![image](https://user-images.githubusercontent.com/66129042/95905937-76bfb580-0d67-11eb-80fa-08588a6ccda8.png)
@kaiquelupo @functionalstoic

**Comment by kaiquelupo** [comment]
Hey @pledgera! Thank you for reaching out. As a first step, would you check all environment variables from both Twilio Functions and Flex Plugin. They are quite important and normally this is the issue.

1. For the Twilio Functions, you can go to `Twilio Console > Functions > Services > Select the Service` and you are going to see a `Environment Variables` panel in the left bottom of the page. Check all the environment variables and see if everything is correct.     

2. For the plugin, check if you are using the correct `.env` file. When deploying/building, we are using the `.env.production` file with the following variables: REACT_APP_SERVICE_BASE_URL, REACT_APP_TASK_CHANNEL_SID. 

Let me know what you find out ;)

**Comment by pledgera** [comment]
Hey @kaiquelupo Thank you for your response!  Srikanth responded with "Thank you for the details. We thought the same and verified all environment variables and SIDs multiple times. All seem to be configured correctly. " Is there anything else they could check?  They asked for a call with you but I have already told them that their Professional Services Engagement has completed.

**Comment by pledgera** [comment]
@kaiquelupo Thank you for your help!  They figured it out the issue was with double quotes vs. single quotes in .env file.

**Comment by kaiquelupo** [comment]
Perfect! Glad it worked @pledgera :D

**Comment by pledgera** [comment]
@kaiquelupo @functionalstoic sorry to bother you but they are now having the same issue where the agent-to agent calling isn't working.  The receiving agent phone never rings.  However, they said there are no errors when they debug this time and nothing in try-catch block. The receiving agent just doesn't get the calls.  Are there any other ways to find any applicable errors?
