### ISSUE TITLE
Hide the "Assign a Queue" with CSS Styling

### ISSUE THREAD

**Issue by pledgera** [twilio-professional-services/flex-dialpad-addon-plugin#13]
Hi @kaiquelupo Slalom wants to hide the "Assign a Queue" and Terence suggested using CSS Styling.  Slalom cannot find the name of the component that they need to hide.  Would you be able to provide the name of the component to high the "Assign a Queue"?

**Comment by kaiquelupo** [comment]
Hey @pledgera. Now it is possible to remove the label and the dropdown using the Flex UI interface directly. To do that, just add the next two lines to the `init` method of their plugin: 

```
    flex.OutboundDialerPanel.Content.remove("queue-select-caption");
    flex.OutboundDialerPanel.Content.remove("queue-select");
```

**Comment by kaiquelupo** [comment]
In fact, by doing what I've suggested previously you will not be able to make a call. So, as Terence suggested the best way is using CSS. You can add a `styles.css` file to `src` with the following content:

```
.Twilio-OutboundDialerPanel-QueueSelect-Caption {
    display: none;
}
.Twilio-OutboundDialerPanel-QueueSelect {
    display: none !important;
}
```

Then, you should add the following line to src/DialpadPlugin.js:

```
import "./styles.css";
```
