### ISSUE TITLE
Deployment to Production - Unable to Display Agents in Dropdown

### ISSUE THREAD

**Issue by pledgera** [twilio-professional-services/flex-dialpad-addon-plugin#14]
Upon deploying to production, Slalom is running into some limitations with the sync SDK not being able to display all of their agents because they have more than 1000.  Is there any guidance to what they would need to change in order to show all of their agents in the dropdown @kaiquelupo ?
![image](https://user-images.githubusercontent.com/66129042/96720435-c2cab580-1378-11eb-8bad-6d41e52bdf31.png)

**Comment by kaiquelupo** [comment]
Hey @pledgera! We've just updated the plugin to fix this issue. Now it is possible to search for any agent even if he/she was not in the initial list. However, note that the plugin from the screenshot is a even older version of the plugin. Now, using the new release, you will get search and the fix all together.

**Comment by pledgera** [comment]
@kaiquelupo Thank you for the update.  Will this also increase the agent limitation?
